using System.IO;
using System.Text;

namespace L4D2ServerManager
{
    public class ServerConfigurator
    {
        private readonly string cfgPath;

        public ServerConfigurator(string path)
        {
            cfgPath = path;
        }

        public void GenerateConfig(string hostname, int maxPlayers, string steamGroup)
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// =======================================");
            sb.AppendLine("// GENERATED BY L4D2 ULTIMATE MANAGER");
            sb.AppendLine("// =======================================");
            sb.AppendLine("");

            // 1. Tên máy chủ và Mật khẩu
            sb.AppendLine($"hostname \"{hostname}\"");
            sb.AppendLine("rcon_password \"admin12345\" // Nhớ đổi mật khẩu RCON");
            sb.AppendLine("sv_password \"\" // Để trống để public");
            sb.AppendLine("");

            // 2. Số lượng người chơi
            sb.AppendLine($"sv_maxplayers {maxPlayers}");
            sb.AppendLine($"sv_visiblemaxplayers {maxPlayers}");
            // Mẹo: Để thực sự phá giới hạn 8 người, bạn sẽ cần cài thêm SourceMod + Left4DHooks. 
            // Nhưng CFG này đã chuẩn bị sẵn cvar cho bạn.
            sb.AppendLine("");

            // 3. Cho phép hiện trên danh sách Campaign & Chơi trực tiếp không cần Lobby
            sb.AppendLine("sv_allow_lobby_connect_only 0");
            sb.AppendLine("sv_lan 0");  // BẮT BUỘC: Đặt là 0 để máy chủ hiển thị trên Internet
            sb.AppendLine("sv_gametypes \"coop,versus,survival,scavenge\"");
            sb.AppendLine("mp_gamemode \"coop\"");
            sb.AppendLine("sm_unreserve // Dành cho SourceMod: Cho phép người lạ join giữa chừng");
            sb.AppendLine("");

            // 4. Steam Group (Nhóm Steam)
            if (!string.IsNullOrEmpty(steamGroup))
            {
                sb.AppendLine($"sv_steamgroup \"{steamGroup}\"");
                sb.AppendLine("sv_steamgroup_exclusive 0 // Đặt 0 để không ép buộc chỉ mem group mới được vào");
            }
            sb.AppendLine("");

            // 5. Tối ưu hóa Mạng (Chống Lag, Ổn định Tickrate)
            sb.AppendLine("sv_minrate 30000");
            sb.AppendLine("sv_maxrate 100000");
            sb.AppendLine("sv_mincmdrate 30");
            sb.AppendLine("sv_maxcmdrate 100");
            sb.AppendLine("sv_minupdaterate 30");
            sb.AppendLine("sv_maxupdaterate 100");
            sb.AppendLine("net_splitpacket_maxrate 50000");
            sb.AppendLine("");

            // 6. Khu vực và Cheat
            sb.AppendLine("sv_cheats 0");
            sb.AppendLine("sv_region 255 // 255 = Global, 4 = Asia");

            // Lưu ra file server.cfg
            File.WriteAllText(cfgPath, sb.ToString());
        }
    }
}